
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.eseo.jee.taxi;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-03-13T13:34:18.650+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(
                      serviceName = "GestionTaxiService",
                      portName = "GestionTaxiPort",
                      targetNamespace = "http://projet.jee.eseo/",
                      wsdlLocation = "http://192.168.4.204:8080/GestionReservationTaxi/services/GestionTaxiPort?wsdl",
                      endpointInterface = "fr.eseo.jee.taxi.SEITaxi")

public class GestionTaxiPortImpl implements SEITaxi {

    private static final Logger LOG = Logger.getLogger(GestionTaxiPortImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.eseo.jee.taxi.SEITaxi#trouverTaxi(fr.eseo.jee.taxi.Taxi arg0, java.lang.String arg1)*
     */
    public java.util.List<fr.eseo.jee.taxi.Taxi> trouverTaxi(fr.eseo.jee.taxi.Taxi arg0, java.lang.String arg1) {
        LOG.info("Executing operation trouverTaxi");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            java.util.List<fr.eseo.jee.taxi.Taxi> _return = new java.util.ArrayList<fr.eseo.jee.taxi.Taxi>();
            fr.eseo.jee.taxi.Taxi _returnVal1 = new fr.eseo.jee.taxi.Taxi();
            _returnVal1.setCategorie("Categorie-618931955");
            _returnVal1.setCodeTaxi(1642736380);
            _returnVal1.setTarif(0.6380347139360206);
            _returnVal1.setVille("Ville-97505984");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.jee.taxi.SEITaxi#payerTaxi(int arg0)*
     */
    public java.lang.String payerTaxi(int arg0) {
        LOG.info("Executing operation payerTaxi");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-270171107";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.jee.taxi.SEITaxi#connexion(java.lang.String arg0, java.lang.String arg1)*
     */
    public fr.eseo.jee.taxi.Client connexion(java.lang.String arg0, java.lang.String arg1) {
        LOG.info("Executing operation connexion");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            fr.eseo.jee.taxi.Client _return = new fr.eseo.jee.taxi.Client();
            _return.setCodeClient(336036568);
            _return.setEmail("Email-1757800348");
            _return.setNom("Nom869925688");
            _return.setPassword("Password830943013");
            _return.setPrenom("Prenom-327480650");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.jee.taxi.SEITaxi#reserverTaxi(fr.eseo.jee.taxi.ReservationTaxi arg0)*
     */
    public int reserverTaxi(fr.eseo.jee.taxi.ReservationTaxi arg0) {
        LOG.info("Executing operation reserverTaxi");
        System.out.println(arg0);
        try {
            int _return = -2066434041;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.jee.taxi.SEITaxi#creerCompte(fr.eseo.jee.taxi.Client arg0)*
     */
    public int creerCompte(fr.eseo.jee.taxi.Client arg0) {
        LOG.info("Executing operation creerCompte");
        System.out.println(arg0);
        try {
            int _return = -1175306578;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.jee.taxi.SEITaxi#nbreReservationsClient(int arg0)*
     */
    public java.util.List<fr.eseo.jee.taxi.ReservationTaxi> nbreReservationsClient(int arg0) {
        LOG.info("Executing operation nbreReservationsClient");
        System.out.println(arg0);
        try {
            java.util.List<fr.eseo.jee.taxi.ReservationTaxi> _return = new java.util.ArrayList<fr.eseo.jee.taxi.ReservationTaxi>();
            fr.eseo.jee.taxi.ReservationTaxi _returnVal1 = new fr.eseo.jee.taxi.ReservationTaxi();
            _returnVal1.setCodeClient(2100245770);
            _returnVal1.setCodeReservation(-803671348);
            _returnVal1.setCodeTaxi(-2079181845);
            _returnVal1.setDate("Date-598101057");
            _returnVal1.setPaiement(true);
            _returnVal1.setVille("Ville239530157");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.jee.taxi.SEITaxi#annulerTaxi(int arg0)*
     */
    public java.lang.String annulerTaxi(int arg0) {
        LOG.info("Executing operation annulerTaxi");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1462168457";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
