package fr.eseo.jee.taxi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-03-13T13:34:18.683+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://projet.jee.eseo/", name = "SEITaxi")
@XmlSeeAlso({ObjectFactory.class})
public interface SEITaxi {

    @WebMethod(action = "urn:TrouverTaxi")
    @RequestWrapper(localName = "trouverTaxi", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.TrouverTaxi")
    @ResponseWrapper(localName = "trouverTaxiResponse", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.TrouverTaxiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.eseo.jee.taxi.Taxi> trouverTaxi(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.jee.taxi.Taxi arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod(action = "urn:PayerTaxi")
    @RequestWrapper(localName = "payerTaxi", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.PayerTaxi")
    @ResponseWrapper(localName = "payerTaxiResponse", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.PayerTaxiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String payerTaxi(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod(action = "urn:Connexion")
    @RequestWrapper(localName = "connexion", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.Connexion")
    @ResponseWrapper(localName = "connexionResponse", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.ConnexionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public fr.eseo.jee.taxi.Client connexion(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebMethod(action = "urn:ReserverTaxi")
    @RequestWrapper(localName = "reserverTaxi", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.ReserverTaxi")
    @ResponseWrapper(localName = "reserverTaxiResponse", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.ReserverTaxiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int reserverTaxi(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.jee.taxi.ReservationTaxi arg0
    );

    @WebMethod(action = "urn:CreerCompte")
    @RequestWrapper(localName = "creerCompte", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.CreerCompte")
    @ResponseWrapper(localName = "creerCompteResponse", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.CreerCompteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int creerCompte(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.jee.taxi.Client arg0
    );

    @WebMethod(action = "urn:NbreReservationsClient")
    @RequestWrapper(localName = "nbreReservationsClient", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.NbreReservationsClient")
    @ResponseWrapper(localName = "nbreReservationsClientResponse", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.NbreReservationsClientResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.eseo.jee.taxi.ReservationTaxi> nbreReservationsClient(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod(action = "urn:AnnulerTaxi")
    @RequestWrapper(localName = "annulerTaxi", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.AnnulerTaxi")
    @ResponseWrapper(localName = "annulerTaxiResponse", targetNamespace = "http://projet.jee.eseo/", className = "fr.eseo.jee.taxi.AnnulerTaxiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String annulerTaxi(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
