
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package fr.eseo.jee;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-03-06T15:37:03.949+01:00
 * Generated source version: 3.3.0
 *
 */

@javax.jws.WebService(
                      serviceName = "GestionVisitesService",
                      portName = "GestionVisitesPort",
                      targetNamespace = "http://jee.eseo.fr/",
                      wsdlLocation = "http://192.168.4.197:8080/GestionVisites/services/GestionVisitesPort?wsdl",
                      endpointInterface = "fr.eseo.jee.SEIGestionVisites")

public class GestionVisitesPortImpl implements SEIGestionVisites {

    private static final Logger LOG = Logger.getLogger(GestionVisitesPortImpl.class.getName());

    /* (non-Javadoc)
     * @see fr.eseo.jee.SEIGestionVisites#annulerVisite(java.lang.String arg0)*
     */
    public boolean annulerVisite(java.lang.String arg0) {
        LOG.info("Executing operation annulerVisite");
        System.out.println(arg0);
        try {
            boolean _return = true;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.jee.SEIGestionVisites#reserverVisite(fr.eseo.jee.ReservationVisite arg0)*
     */
    public java.lang.String reserverVisite(fr.eseo.jee.ReservationVisite arg0) {
        LOG.info("Executing operation reserverVisite");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-605814491";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.jee.SEIGestionVisites#payerVisite(java.lang.String arg0)*
     */
    public java.lang.String payerVisite(java.lang.String arg0) {
        LOG.info("Executing operation payerVisite");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return2103982504";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see fr.eseo.jee.SEIGestionVisites#trouverVisite(fr.eseo.jee.Visite arg0)*
     */
    public java.util.List<fr.eseo.jee.Visite> trouverVisite(fr.eseo.jee.Visite arg0) {
        LOG.info("Executing operation trouverVisite");
        System.out.println(arg0);
        try {
            java.util.List<fr.eseo.jee.Visite> _return = new java.util.ArrayList<fr.eseo.jee.Visite>();
            fr.eseo.jee.Visite _returnVal1 = new fr.eseo.jee.Visite();
            _returnVal1.setCodeVisite("CodeVisite298533300");
            _returnVal1.setDateVisite("DateVisite-1185346610");
            _returnVal1.setPrix(0.04747631566313859);
            _returnVal1.setTypeVisite("TypeVisite-449728574");
            _returnVal1.setVille("Ville1421446368");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
