
package fr.eseo.jee;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-03-06T15:37:03.794+01:00
 * Generated source version: 3.3.0
 *
 */
public final class SEIGestionVisites_GestionVisitesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://jee.eseo.fr/", "GestionVisitesService");

    private SEIGestionVisites_GestionVisitesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GestionVisitesService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GestionVisitesService ss = new GestionVisitesService(wsdlURL, SERVICE_NAME);
        SEIGestionVisites port = ss.getGestionVisitesPort();

        {
        System.out.println("Invoking annulerVisite...");
        java.lang.String _annulerVisite_arg0 = "_annulerVisite_arg01717272874";
        boolean _annulerVisite__return = port.annulerVisite(_annulerVisite_arg0);
        System.out.println("annulerVisite.result=" + _annulerVisite__return);


        }
        {
        System.out.println("Invoking reserverVisite...");
        fr.eseo.jee.ReservationVisite _reserverVisite_arg0 = new fr.eseo.jee.ReservationVisite();
        _reserverVisite_arg0.setCodeClient("CodeClient1630891643");
        _reserverVisite_arg0.setCodeReservation("CodeReservation157659793");
        _reserverVisite_arg0.setCodeVisite(-388564461);
        _reserverVisite_arg0.setNbPersonnes(1431260939);
        _reserverVisite_arg0.setPaiementEffectue(false);
        java.lang.String _reserverVisite__return = port.reserverVisite(_reserverVisite_arg0);
        System.out.println("reserverVisite.result=" + _reserverVisite__return);


        }
        {
        System.out.println("Invoking payerVisite...");
        java.lang.String _payerVisite_arg0 = "_payerVisite_arg0-1887723550";
        java.lang.String _payerVisite__return = port.payerVisite(_payerVisite_arg0);
        System.out.println("payerVisite.result=" + _payerVisite__return);


        }
        {
        System.out.println("Invoking trouverVisite...");
        fr.eseo.jee.Visite _trouverVisite_arg0 = new fr.eseo.jee.Visite();
        _trouverVisite_arg0.setCodeVisite("CodeVisite-1063367088");
        _trouverVisite_arg0.setDateVisite("DateVisite1733138305");
        _trouverVisite_arg0.setPrix(0.6680937869971911);
        _trouverVisite_arg0.setTypeVisite("TypeVisite-1379346691");
        _trouverVisite_arg0.setVille("Ville-1487518163");
        java.util.List<fr.eseo.jee.Visite> _trouverVisite__return = port.trouverVisite(_trouverVisite_arg0);
        System.out.println("trouverVisite.result=" + _trouverVisite__return);


        }

        System.exit(0);
    }

}
