package fr.eseo.jee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-03-09T09:44:54.335+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://jee.eseo.fr/", name = "SEIGestionVisites")
@XmlSeeAlso({ObjectFactory.class})
public interface SEIGestionVisites {

    @WebMethod
    @RequestWrapper(localName = "annulerVisite", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.AnnulerVisite")
    @ResponseWrapper(localName = "annulerVisiteResponse", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.AnnulerVisiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean annulerVisite(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "reserverVisite", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.ReserverVisite")
    @ResponseWrapper(localName = "reserverVisiteResponse", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.ReserverVisiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String reserverVisite(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.jee.ReservationVisite arg0
    );

    @WebMethod
    @RequestWrapper(localName = "payerVisite", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.PayerVisite")
    @ResponseWrapper(localName = "payerVisiteResponse", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.PayerVisiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String payerVisite(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "trouverVisite", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.TrouverVisite")
    @ResponseWrapper(localName = "trouverVisiteResponse", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.TrouverVisiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.eseo.jee.Visite> trouverVisite(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.jee.Visite arg0
    );
}
