
package fr.eseo.jee.visite;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-03-13T14:12:36.795+01:00
 * Generated source version: 3.3.0
 *
 */
public final class SEIGestionVisites_GestionVisitesPort_Client {

    private static final QName SERVICE_NAME = new QName("http://jee.eseo.fr/", "GestionVisitesService");

    private SEIGestionVisites_GestionVisitesPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GestionVisitesService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GestionVisitesService ss = new GestionVisitesService(wsdlURL, SERVICE_NAME);
        SEIGestionVisites port = ss.getGestionVisitesPort();

        {
        System.out.println("Invoking annulerVisite...");
        java.lang.String _annulerVisite_arg0 = "_annulerVisite_arg0-1547534161";
        int _annulerVisite_arg1 = -119977883;
        boolean _annulerVisite__return = port.annulerVisite(_annulerVisite_arg0, _annulerVisite_arg1);
        System.out.println("annulerVisite.result=" + _annulerVisite__return);


        }
        {
        System.out.println("Invoking reserverVisite...");
        fr.eseo.jee.visite.ReservationVisite _reserverVisite_arg0 = new fr.eseo.jee.visite.ReservationVisite();
        _reserverVisite_arg0.setCodeClient(392167762);
        _reserverVisite_arg0.setCodeReservation("CodeReservation115371439");
        _reserverVisite_arg0.setCodeVisite("CodeVisite501246817");
        _reserverVisite_arg0.setNbPersonnes(-1638776708);
        _reserverVisite_arg0.setPaiementEffectue(true);
        java.lang.String _reserverVisite__return = port.reserverVisite(_reserverVisite_arg0);
        System.out.println("reserverVisite.result=" + _reserverVisite__return);


        }
        {
        System.out.println("Invoking payerVisite...");
        java.lang.String _payerVisite_arg0 = "_payerVisite_arg01434105952";
        java.lang.String _payerVisite__return = port.payerVisite(_payerVisite_arg0);
        System.out.println("payerVisite.result=" + _payerVisite__return);


        }
        {
        System.out.println("Invoking trouverVisite...");
        fr.eseo.jee.visite.Visite _trouverVisite_arg0 = new fr.eseo.jee.visite.Visite();
        _trouverVisite_arg0.setCodeVisite("CodeVisite1424847412");
        _trouverVisite_arg0.setDateVisite("DateVisite-1409044036");
        _trouverVisite_arg0.setPrix(0.47752472764822373);
        _trouverVisite_arg0.setTypeVisite("TypeVisite-1367831046");
        _trouverVisite_arg0.setVille("Ville-656246683");
        java.util.List<fr.eseo.jee.visite.Visite> _trouverVisite__return = port.trouverVisite(_trouverVisite_arg0);
        System.out.println("trouverVisite.result=" + _trouverVisite__return);


        }

        System.exit(0);
    }

}
