package fr.eseo.jee.visite;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2020-03-13T14:12:36.950+01:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://jee.eseo.fr/", name = "SEIGestionVisites")
@XmlSeeAlso({ObjectFactory.class})
public interface SEIGestionVisites {

    @WebMethod
    @RequestWrapper(localName = "annulerVisite", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.visite.AnnulerVisite")
    @ResponseWrapper(localName = "annulerVisiteResponse", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.visite.AnnulerVisiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean annulerVisite(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );

    @WebMethod
    @RequestWrapper(localName = "reserverVisite", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.visite.ReserverVisite")
    @ResponseWrapper(localName = "reserverVisiteResponse", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.visite.ReserverVisiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String reserverVisite(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.jee.visite.ReservationVisite arg0
    );

    @WebMethod
    @RequestWrapper(localName = "payerVisite", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.visite.PayerVisite")
    @ResponseWrapper(localName = "payerVisiteResponse", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.visite.PayerVisiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String payerVisite(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "trouverVisite", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.visite.TrouverVisite")
    @ResponseWrapper(localName = "trouverVisiteResponse", targetNamespace = "http://jee.eseo.fr/", className = "fr.eseo.jee.visite.TrouverVisiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<fr.eseo.jee.visite.Visite> trouverVisite(
        @WebParam(name = "arg0", targetNamespace = "")
        fr.eseo.jee.visite.Visite arg0
    );
}
